version: '3'
services:
  app:
    container_name: tebex-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      NODE_ENV: development
      KEYCLOAK_URL: ${KEYCLOAK_URL}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - mongodb
    networks:
      - tebex

  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE=tebex
    container_name: tebex-mongo
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      - tebex
networks:
  tebex:
    external: true
