import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { City } from 'src/cities/schema/city.schema';
import { District } from 'src/districts/schema/district.schema';

@Injectable()
export class DistrictSeeder {
  constructor(@InjectModel(District.name) private districtModel: Model<District>,
    @InjectModel(City.name) private cityModel: Model<City>
  ) { }
  async seed() {
    const RiyadhCity = await this.cityModel.findOne({ name: 'Riyadh' });
    if (!RiyadhCity) {
      return;
    }
    const districts = await this.districtModel.find({ city: RiyadhCity._id });
    if (districts.length) {
      return;
    }
    const districtNames = [
      { "name_ar": "الرمال", "city": RiyadhCity._id },
      { "name_ar": "اليرموك", "city": RiyadhCity._id },
      { "name_ar": "المونسية", "city": RiyadhCity._id },
      { "name_ar": "النهضة", "city": RiyadhCity._id },
      { "name_ar": "اشبيلية", "city": RiyadhCity._id },
      { "name_ar": "الخليج", "city": RiyadhCity._id },
      { "name_ar": "الملز", "city": RiyadhCity._id },
      { "name_ar": "الملك فيصل", "city": RiyadhCity._id },
      { "name_ar": "النظيم", "city": RiyadhCity._id },
      { "name_ar": "قرطبة", "city": RiyadhCity._id },
      { "name_ar": "السعادة", "city": RiyadhCity._id },
      { "name_ar": "الجنادرية", "city": RiyadhCity._id },
      { "name_ar": "النسيم الغربي", "city": RiyadhCity._id },
      { "name_ar": "الشهداء", "city": RiyadhCity._id },
      { "name_ar": "القادسية", "city": RiyadhCity._id },
      { "name_ar": "المعيزلة", "city": RiyadhCity._id },
      { "name_ar": "الروضة", "city": RiyadhCity._id },
      { "name_ar": "السلام", "city": RiyadhCity._id },
      { "name_ar": "الفيحاء", "city": RiyadhCity._id },
      { "name_ar": "القدس", "city": RiyadhCity._id },
      { "name_ar": "غرناطة", "city": RiyadhCity._id },
      { "name_ar": "الروابي", "city": RiyadhCity._id },
      { "name_ar": "الازدهار", "city": RiyadhCity._id },
      { "name_ar": "الاندلس", "city": RiyadhCity._id },
      { "name_ar": "المنار", "city": RiyadhCity._id },
      { "name_ar": "الحمراء", "city": RiyadhCity._id },
      { "name_ar": "الريان", "city": RiyadhCity._id },
      { "name_ar": "الجزيرة", "city": RiyadhCity._id },
      { "name_ar": "الصفا", "city": RiyadhCity._id },
      { "name_ar": "الرماية", "city": RiyadhCity._id },
      { "name_ar": "الملك عبدالعزيز", "city": RiyadhCity._id },
      { "name_ar": "النسيم الشرقي", "city": RiyadhCity._id },
      { "name_ar": "الندوة", "city": RiyadhCity._id },
      { "name_ar": "الملقا", "city": RiyadhCity._id },
      { "name_ar": "النرجس", "city": RiyadhCity._id },
      { "name_ar": "العارض", "city": RiyadhCity._id },
      { "name_ar": "الياسمين", "city": RiyadhCity._id },
      { "name_ar": "الصحافة", "city": RiyadhCity._id },
      { "name_ar": "العقيق", "city": RiyadhCity._id },
      { "name_ar": "القيروان", "city": RiyadhCity._id },
      { "name_ar": "العليا", "city": RiyadhCity._id },
      { "name_ar": "حطين", "city": RiyadhCity._id },
      { "name_ar": "السليمانية", "city": RiyadhCity._id },
      { "name_ar": "المصيف", "city": RiyadhCity._id },
      { "name_ar": "التعاون", "city": RiyadhCity._id },
      { "name_ar": "الربيع", "city": RiyadhCity._id },
      { "name_ar": "الفلاح", "city": RiyadhCity._id },
      { "name_ar": "الوادي", "city": RiyadhCity._id },
      { "name_ar": "النزهة", "city": RiyadhCity._id },
      { "name_ar": "الملك عبدالله", "city": RiyadhCity._id },
      { "name_ar": "الندى", "city": RiyadhCity._id },
      { "name_ar": "الغدير", "city": RiyadhCity._id },
      { "name_ar": "الورود", "city": RiyadhCity._id },
      { "name_ar": "الملك فهد", "city": RiyadhCity._id },
      { "name_ar": "المروج", "city": RiyadhCity._id },
      { "name_ar": "النفل", "city": RiyadhCity._id },
      { "name_ar": "الرحمانية", "city": RiyadhCity._id },
      { "name_ar": "المرسلات", "city": RiyadhCity._id },
      { "name_ar": "النخيل", "city": RiyadhCity._id },
      { "name_ar": "الواحة", "city": RiyadhCity._id },
      { "name_ar": "المغرزات", "city": RiyadhCity._id },
      { "name_ar": "المؤتمرات", "city": RiyadhCity._id },
      { "name_ar": "المحمدية", "city": RiyadhCity._id },
      { "name_ar": "الملك خالد الدولي", "city": RiyadhCity._id },
      { "name_ar": "صلاح الدين", "city": RiyadhCity._id },
      { "name_ar": "المعذر الشمالي", "city": RiyadhCity._id },
      { "name_ar": "بنبان", "city": RiyadhCity._id },
      { "name_ar": "جامعة الامام محمد بن سعود الاسلامية", "city": RiyadhCity._id },
      { "name_ar": "جامعة الملك سعود", "city": RiyadhCity._id },
      { "name_ar": "جامعة الأميرة نورة", "city": RiyadhCity._id },
      { "name_ar": "مركز الملك عبدالله للدراسات والبحوث", "city": RiyadhCity._id },
      { "name_ar": "ظهرة لبن", "city": RiyadhCity._id },
      { "name_ar": "طويق", "city": RiyadhCity._id },
      { "name_ar": "نمار", "city": RiyadhCity._id },
      { "name_ar": "العريجاء الغربية", "city": RiyadhCity._id },
      { "name_ar": "المهدية", "city": RiyadhCity._id },
      { "name_ar": "الحزم", "city": RiyadhCity._id },
      { "name_ar": "السويدي الغربي", "city": RiyadhCity._id },
      { "name_ar": "العريجاء الوسطى", "city": RiyadhCity._id },
      { "name_ar": "ام الحمام الغربي", "city": RiyadhCity._id },
      { "name_ar": "الزهرة", "city": RiyadhCity._id },
      { "name_ar": "البديعة", "city": RiyadhCity._id },
      { "name_ar": "السويدي", "city": RiyadhCity._id },
      { "name_ar": "عرقة", "city": RiyadhCity._id },
      { "name_ar": "الجرادية", "city": RiyadhCity._id },
      { "name_ar": "ظهرة البديعة", "city": RiyadhCity._id },
      { "name_ar": "ديراب", "city": RiyadhCity._id },
      { "name_ar": "لبن", "city": RiyadhCity._id },
      { "name_ar": "الدريهمية", "city": RiyadhCity._id },
      { "name_ar": "ام الحمام الشرقي", "city": RiyadhCity._id },
      { "name_ar": "سلطانة", "city": RiyadhCity._id },
      { "name_ar": "شبرا", "city": RiyadhCity._id },
      { "name_ar": "الرائد", "city": RiyadhCity._id },
      { "name_ar": "الرفيعة", "city": RiyadhCity._id },
      { "name_ar": "الفاخرية", "city": RiyadhCity._id },
      { "name_ar": "العريجاء", "city": RiyadhCity._id },
      { "name_ar": "عليشة", "city": RiyadhCity._id },
      { "name_ar": "الخزامى", "city": RiyadhCity._id },
      { "name_ar": "الشرفية", "city": RiyadhCity._id },
      { "name_ar": "المعذر", "city": RiyadhCity._id },
      { "name_ar": "الهدا", "city": RiyadhCity._id },
      { "name_ar": "صياح", "city": RiyadhCity._id },
      { "name_ar": "الناصرية", "city": RiyadhCity._id },
      { "name_ar": "العريجاء الأوسط", "city": RiyadhCity._id },
      { "name_ar": "الخزامي", "city": RiyadhCity._id },
      { "name_ar": "السفارات", "city": RiyadhCity._id },
      { "name_ar": "وادي لبن", "city": RiyadhCity._id },
      { "name_ar": "العوالي", "city": RiyadhCity._id },
      { "name_ar": "ضاحية نمار", "city": RiyadhCity._id },
      { "name_ar": "العزيزية", "city": RiyadhCity._id },
      { "name_ar": "الدار البيضاء", "city": RiyadhCity._id },
      { "name_ar": "بدر", "city": RiyadhCity._id },
      { "name_ar": "عكاظ", "city": RiyadhCity._id },
      { "name_ar": "الشفا", "city": RiyadhCity._id },
      { "name_ar": "أحد", "city": RiyadhCity._id },
      { "name_ar": "السلي", "city": RiyadhCity._id },
      { "name_ar": "المروة", "city": RiyadhCity._id },
      { "name_ar": "المناخ", "city": RiyadhCity._id },
      { "name_ar": "الحائر", "city": RiyadhCity._id },
      { "name_ar": "طيبة", "city": RiyadhCity._id },
      { "name_ar": "البرية", "city": RiyadhCity._id },
      { "name_ar": "المشاعل", "city": RiyadhCity._id },
      { "name_ar": "المصانع", "city": RiyadhCity._id },
      { "name_ar": "الاسكان", "city": RiyadhCity._id },
      { "name_ar": "الدفاع", "city": RiyadhCity._id },
      { "name_ar": "المدينة الصناعية الجديدة", "city": RiyadhCity._id },
      { "name_ar": "هيت", "city": RiyadhCity._id },
      { "name_ar": "عريض", "city": RiyadhCity._id },
      { "name_ar": "الضباط", "city": RiyadhCity._id },
      { "name_ar": "المربع", "city": RiyadhCity._id },
      { "name_ar": "غبيرة", "city": RiyadhCity._id },
      { "name_ar": "اليمامة", "city": RiyadhCity._id },
      { "name_ar": "منفوحة الجديدة", "city": RiyadhCity._id },
      { "name_ar": "الشميسي", "city": RiyadhCity._id },
      { "name_ar": "منفوحة", "city": RiyadhCity._id },
      { "name_ar": "الوزارات", "city": RiyadhCity._id },
      { "name_ar": "جرير", "city": RiyadhCity._id },
      { "name_ar": "عتيقة", "city": RiyadhCity._id },
      { "name_ar": "المنصورة", "city": RiyadhCity._id },
      { "name_ar": "الربوة", "city": RiyadhCity._id },
      { "name_ar": "الزهراء", "city": RiyadhCity._id },
      { "name_ar": "ام سليم", "city": RiyadhCity._id },
      { "name_ar": "العمل", "city": RiyadhCity._id },
      { "name_ar": "الصالحية", "city": RiyadhCity._id },
      { "name_ar": "الخالدية", "city": RiyadhCity._id },
      { "name_ar": "الوشام", "city": RiyadhCity._id },
      { "name_ar": "الديرة", "city": RiyadhCity._id },
      { "name_ar": "ثليم", "city": RiyadhCity._id },
      { "name_ar": "جبرة", "city": RiyadhCity._id },
      { "name_ar": "سكيرينة", "city": RiyadhCity._id },
      { "name_ar": "الفوطة", "city": RiyadhCity._id },
      { "name_ar": "النموذجية", "city": RiyadhCity._id },
      { "name_ar": "البطيحا", "city": RiyadhCity._id },
      { "name_ar": "الدوبية", "city": RiyadhCity._id },
      { "name_ar": "الصناعية", "city": RiyadhCity._id },
      { "name_ar": "العود", "city": RiyadhCity._id },
      { "name_ar": "الفاروق", "city": RiyadhCity._id },
      { "name_ar": "الفيصلية", "city": RiyadhCity._id }
    ];

    await this.districtModel.insertMany(districtNames);
  }
}
